### ISSUE TITLE
Please add nested tabs ability in the tabs widget

### ISSUE THREAD

**Issue by bentalgad** [Crocoblock/jet-widgets#1]
The height of the tab needs to be auto adjusting when it's content changes. it's critical not only for nested tabs but for a lot of other elements which has a changing height.

**Comment by kaskad88** [comment]
Hi

Sorry for the inconvenience, we just released a patch for this issue (Jet Tabs v1.1.4), please update the plugin and let me know if it fixes your problem.

Thanks

**Comment by bentalgad** [comment]
It does! Thanks!
