### ISSUE TITLE
Switcher RTL bug

### ISSUE THREAD

**Issue by bentalgad** [Crocoblock/jet-widgets#2]
The Switcher doesn't work good on a RTL site. it looks like that:
![screen shot 2018-11-27 at 18 36 08](https://user-images.githubusercontent.com/23374215/49096495-566dd700-f273-11e8-90b8-44a2830523a8.png)

**Comment by ZemezLab** [comment]
done

**Comment by bentalgad** [comment]
Great! Thanks!
